### PR TITLE
Backported Audio Fix

### PR DESCRIPTION
**Pull request by Stoweneele**
Tested alone with no issues. Further testing recommended.

### CODE REVIEW

**Comment by NoShotz** [comment]
Fails to compile for me. https://i.imgur.com/Glmcuib.png

**Comment by Stowneele** [comment]
Was able to play through The Ark without crashing. Once the compile issue is resolved this should be good to go.

**Comment by Akarias** [comment]
Building here just fine.

**Comment by blackdimund** [comment]
same error as NoShotz

**Comment by NoShotz** [comment]
Even after reinstalling VS, it doesn't compile for me.

**Comment by NoShotz** [comment]
> Compile as debug if you are not already.

That seems to have fixed it. I don't get why I would have to do a debug build, I prefer to do release builds as they run better than debug builds performance wise.

**Comment by blackdimund** [comment]
Yep same, debug can compile but it stuck on loading on lobby at 0%, of course I am still trying to port 100_citadel which is still giving me problems anyways

**Comment by WRTuL** [comment]
The compile issue is fixed by changing the optimization in VS to MinimumS Size (/O1) as seen here https://cdn.discordapp.com/attachments/496592166307627009/506530730390585365/unknown.png

**Comment by danger89** [comment]
Merge?

**Comment by Akarias** [comment]
There are still crash related issues when this is applied, but it seems to vary between users. Not so sure until someone pinns down what is causing it.

**Pull request closed without merging**
